### ISSUE TITLE
Not working when testing with 3.7.2

### ISSUE THREAD

**Issue by creativebuild** [joclin/arrowfy#1]
Open .sketchplugin file and nothing happens. 

But congrats on sorting arrow heads out (when it works) in Sketch, they were uuuugly.

**Comment by jonokane** [comment]
Sadly still not working. Would love better arrowheads for Sketch, please!

**Comment by Verdi** [comment]
Just tried it with Sketch 39 and it doesn't seem to work. This would save me sooooo much time.

**Comment by joclin** [comment]
Should be fixed now!
