### ISSUE TITLE
Plugin no longer works on Sketch v45.1

### ISSUE THREAD

**Issue by varunyellina** [joclin/arrowfy#12]
Arrowfy isn't working on the latest Sketch verison.

**Comment by Nat30** [comment]
the same issue.

**Comment by KingScooty** [comment]
Same issue

**Comment by tasha6790** [comment]
Same, any solution @joclin ?

**Comment by joclin** [comment]
Sorry about the delay! I no longer have a working up-to-date copy of Sketch (left my previous job), so I've been waiting until I can purchase the license to fix the plug-in.

**Comment by joclin** [comment]
Alright, done! The version I have is 46.2, so please let me know if you have any issue with your versions.
